### ISSUE TITLE
mismatch for embedding.weight

### ISSUE THREAD

**Issue by Cherrypower** [ShichaoSun/MathDemo#1]
When running the code:
RuntimeError: Error(s) in loading state_dict for EncoderSeq:
	size mismatch for embedding.weight: copying a param with shape torch.Size([4684, 128]) from checkpoint, the shape in current model is torch.Size([4685, 128]).
How to handle it？ Thank you for your reply！

**Comment by ShichaoSun** [comment]
> 

I am so sorry. This code is too old. I am not very sure of some details, but many people have reproduced this code.
